### PR TITLE
Upgrade to Webpack 2, Yarn and remove global imports

### PR DESCRIPTION
**Pull request by hisapy**
@rsjavier14 this is for #15 and #8 ... I still need to fix the webpack dev server stuff but you can review what I have so far.

### CODE REVIEW

**Comment by hisapy** [comment]
With the changes done so far we the build is the following:

```
4.0K	lib/button.js
 16K	lib/card.js
8.0K	lib/dataTable.js
8.0K	lib/grid.js
 76K	lib/index.js
 16K	lib/layout.js
8.0K	lib/menu.js
 76K	lib/spinner.js
8.0K	lib/tabs.js
4.0K	lib/textfield.js
224K	total
```

I hope that we can get even smaller bundles by moving to functional components and some other tweaks but should be for another pull request.

**Comment by rsjavier14** [comment]
wow, You get reduced a lot

**Review by rsjavier14 — COMMENTED** [review]
I think everything is ok

**Comment by hisapy** [comment]
webpack-dev-server and examples fixed and working correctly.

**Review by rsjavier14 — APPROVED** [review]
If everything is working well I think it's ready

**Pull request merged**
